apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://128.199.251.237:5437/task_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "task_db"
            - name: SPRING_DATASOURCE_PASSWORD
              value: '\,4<|F0iABBkAJ4&Y;'
            - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_CLASSROOMSERVICE_URL
              value: "http://classroom-service.hrd-portal.svc.cluster.local:8082"
            - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_AUTHSERVICE_URL
              value: "http://auth-service.hrd-portal.svc.cluster.local:8081"
            - name: SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_RESOURCESERVICE_URL
              value: "http://resource-service.resource-service.svc.cluster.local:8081"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://keycloak.hrdportal.systems/realms/hrd-portal"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
  
            


